import type { ImageSourcePropType } from 'react-native';

export const homeBannerAssets = {
  aggregatorPopular: require('../assets/home/banners/aggregator_popular_banner.webp'),
  categoryBest: require('../assets/home/banners/category_best_banner.webp'),
  categoryForYou: require('../assets/home/banners/category_for_you_banner.webp'),
  jackpotPopular: require('../assets/home/banners/jackpot_popular_banner.webp'),
  luckyWheelPopular: require('../assets/home/banners/lucky_wheel_popular_banner.webp'),
  myAggregator: require('../assets/home/banners/my_aggregator_banner.webp'),
  popularVirtual: require('../assets/home/banners/popular_virtual_banner.webp'),
} satisfies Record<string, ImageSourcePropType>;

export const homePromoAssets = {
  specialEventDefault: require('../assets/home/promo/bg_special_event_default.webp'),
  specialEventSmall: require('../assets/home/promo/bg_special_event_small.webp'),
  specialEventTablet: require('../assets/home/promo/bg_special_event_tablet.webp'),
  promoShopDefaultLarge: require('../assets/home/promo/promo_shop_default_large.webp'),
} satisfies Record<string, ImageSourcePropType>;

export const homeGameAssets = {
  appleCell: require('../assets/home/games/apple_cell.webp'),
  backgroundOdysseyField: require('../assets/home/games/background_odyssey_field.webp'),
  bomb: require('../assets/home/games/bomb.webp'),
  cellBlackBig: require('../assets/home/games/cell_black_big.webp'),
  cellRedBig: require('../assets/home/games/cell_red_big.webp'),
  dragonsGoldArrowCell: require('../assets/home/games/dragons_gold_arrow_cell.webp'),
  dragonsGoldLoseCell: require('../assets/home/games/dragons_gold_lose_cell.webp'),
  dragonsGoldShadowedCell: require('../assets/home/games/dragons_gold_shadowed_cell.webp'),
  dragonsGoldWinCell: require('../assets/home/games/dragons_gold_win_cell.webp'),
  easternNightsArrowCell: require('../assets/home/games/eastern_nights_arrow_cell.png'),
  easternNightsShadowedCell: require('../assets/home/games/eastern_nights_shadowed_cell.png'),
  appleFortunePlaceholder: require('../assets/home/games/game_apple_fortune_placeholder.webp'),
  genericCategoryPlaceholder: require('../assets/home/games/game_category_placeholder.webp'),
  dominoPlaceholder: require('../assets/home/games/game_domino_placeholder.webp'),
  dragonsGoldPlaceholder: require('../assets/home/games/game_dragons_gold_placeholder.jpg'),
  easternNightsPlaceholder: require('../assets/home/games/game_eastern_nights_placeholder.jpg'),
  fruitBlastPlaceholder: require('../assets/home/games/game_fruit_blast_placeholder.webp'),
  guessWhichHandGirlPlaceholder: require('../assets/home/games/game_guess_which_hand_girl_placeholder.webp'),
  guessWhichHandPlaceholder: require('../assets/home/games/game_guess_which_hand_placeholder.webp'),
  luckyWheelNyPlaceholder: require('../assets/home/games/game_lucky_wheel_ny_placeholder.webp'),
  luckyWheelPlaceholder: require('../assets/home/games/game_lucky_wheel_placeholder.webp'),
  minesweeperPlaceholder: require('../assets/home/games/game_minesweeper_placeholder.jpg'),
  odysseyPlaceholder: require('../assets/home/games/game_odyssey_placeholder.webp'),
  residentPlaceholder: require('../assets/home/games/game_resident_placeholder.webp'),
  scratchCardPlaceholder: require('../assets/home/games/game_scratch_card_placeholder.jpg'),
  gamesMania1Puzzle: require('../assets/home/games/games_mania_1_puzzle.webp'),
  gamesMania2Puzzle: require('../assets/home/games/games_mania_2_puzzle.webp'),
  gamesMania2xIcon: require('../assets/home/games/games_mania_2x_ico.webp'),
  gamesMania3Puzzle: require('../assets/home/games/games_mania_3_puzzle.webp'),
  gamesMania4Puzzle: require('../assets/home/games/games_mania_4_puzzle.webp'),
  gamesMania5Puzzle: require('../assets/home/games/games_mania_5_puzzle.webp'),
  gamesManiaBackIcon: require('../assets/home/games/games_mania_back_ico.webp'),
  gamesManiaDiceIcon: require('../assets/home/games/games_mania_dice_ico.webp'),
  gamesManiaFieldCell: require('../assets/home/games/games_mania_field_cell.webp'),
  gamesManiaFreeIcon: require('../assets/home/games/games_mania_free_ico.webp'),
  gamesManiaPuzzleIcon: require('../assets/home/games/games_mania_puzzle_ico.webp'),
  gamesManiaSelectedCell: require('../assets/home/games/games_mania_selected_cell.webp'),
  gamesManiaWheelIcon: require('../assets/home/games/games_mania_wheel_ico.webp'),
  guessWhichHandLeft: require('../assets/home/games/guess_which_hand_left.webp'),
  guessWhichHandLight: require('../assets/home/games/guess_which_hand_light.webp'),
  residentDoorClosed: require('../assets/home/games/ic_resident_door_closed.webp'),
  residentPersonDefault1: require('../assets/home/games/ic_resident_person_default_1.webp'),
  residentPersonDefault2: require('../assets/home/games/ic_resident_person_default_2.webp'),
  residentPersonWin: require('../assets/home/games/ic_resident_person_win.webp'),
  residentSafeGold: require('../assets/home/games/ic_resident_safe_gold.webp'),
  lotteryTicket: require('../assets/home/games/lottery_ticket.webp'),
  spinAndWinWheelCover: require('../assets/home/games/spin_and_win_wheel_cover.webp'),
  wheelOfFortune: require('../assets/home/games/wheel_of_fortune.webp'),
  wheelOfFortuneCover: require('../assets/home/games/wheel_of_fortune_cover.webp'),
} satisfies Record<string, ImageSourcePropType>;

export const homeTeamAssets = {
  dotaPlaceholder: require('../assets/home/teams/dota_team_logo_placeholder.png'),
  footballFieldBackground: require('../assets/home/teams/football_field_background.png'),
} satisfies Record<string, ImageSourcePropType>;

export const homeMediaManifest = {
  local: {
    banners: [
      'aggregator_popular_banner.webp',
      'category_best_banner.webp',
      'category_for_you_banner.webp',
      'jackpot_popular_banner.webp',
      'lucky_wheel_popular_banner.webp',
      'my_aggregator_banner.webp',
      'popular_virtual_banner.webp',
    ],
    games: [
      'background_odyssey_field.webp',
      'dragons_gold_arrow_cell.webp',
      'dragons_gold_lose_cell.webp',
      'game_category_placeholder.webp',
      'game_domino_placeholder.webp',
      'game_lucky_wheel_placeholder.webp',
      'game_lucky_wheel_ny_placeholder.webp',
      'game_resident_placeholder.webp',
      'game_odyssey_placeholder.webp',
      'game_dragons_gold_placeholder.jpg',
      'game_minesweeper_placeholder.jpg',
      'game_guess_which_hand_placeholder.webp',
      'game_scratch_card_placeholder.jpg',
      'game_apple_fortune_placeholder.webp',
      'game_fruit_blast_placeholder.webp',
      'game_eastern_nights_placeholder.jpg',
      'games_mania_back_ico.webp',
      'games_mania_field_cell.webp',
      'games_mania_selected_cell.webp',
      'guess_which_hand_light.webp',
      'ic_resident_person_default_1.webp',
      'ic_resident_person_default_2.webp',
      'ic_resident_person_win.webp',
      'wheel_of_fortune.webp',
      'wheel_of_fortune_cover.webp',
      'spin_and_win_wheel_cover.webp',
      'lottery_ticket.webp',
    ],
    promo: [
      'bg_special_event_default.webp',
      'bg_special_event_small.webp',
      'bg_special_event_tablet.webp',
      'promo_shop_default_large.webp',
    ],
    teams: ['dota_team_logo_placeholder.png', 'football_field_background.png'],
    icons: [
      'ic_one_x_games.xml',
      'ic_one_x_games_new.xml',
      'logo_1x_light.xml',
      'logo_popular_new_1xbet_light.xml',
      'logo_popular_navigation_bar_1xbet_light.xml',
      'team_logo_placeholder.xml',
      'teams_placeholder.xml',
    ],
  },
  remoteUnavailable: [
    '1xGames square/logo posters from /static/img/android/games/game_preview/*',
    'special event banners from SpecialEventInfoModel.banner/backgroundUrl',
    'dynamic team/player logos from TopChamps and related special-event feeds',
    'Aviator tile art for home screen that is not bundled in the APK',
  ],
} as const;
